print("Twinkle, twinkle, little star")
print("How I wonder what you are")
print("Up above the world so high")
print("Like a diamond in the sky")
print("Twinkle, twinkle little s")
print("How I wonder what you are")
print("When the blazing sun is g")
print("When he nothing shines up")
print("Then you show your little")
print("Twinkle, twinkle, all the")
print("Twinkle, twinkle, little ")
print("How I wonder what you are")